# Generated by Django 3.2.12 on 2022-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_board_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='voter',
        ),
        migrations.AddField(
            model_name='board',
            name='voter',
            field=models.ManyToManyField(related_name='vote_question', to='web.Member'),
        ),
    ]
