# Generated by Django 3.2.12 on 2022-03-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20220315_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='voter',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteid', models.AutoField(primary_key=True, serialize=False)),
                ('vote_count', models.IntegerField(default=0)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_boardid', to='web.board')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_userid', to='web.member')),
            ],
            options={
                'db_table': 'db_vote',
            },
        ),
    ]
