# Generated by Django 3.2.12 on 2022-03-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20220315_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=5000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_boardid', to='web.board')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_userid', to='web.member')),
            ],
            options={
                'db_table': 'db_comment',
            },
        ),
    ]
