# Generated by Django 3.2.12 on 2022-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
